language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install tox-travis
script:
  - tox
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.8" ]; then tox -e black; tox -e flake8; tox -e pydocstyle; fi
matrix:
  allow_failures:
    - python: "3.7"
    - python: "3.8"
